name: "DockerPush Client"
on:
  workflow_run:
    workflows: ["BuildSetup"]
    types:
      - completed
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  release:
    types: [ published ]

jobs:
  push_client_image :
    name: Push Docker image to Docker Hub Client
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Push to container
        uses: ./.github/actions/deploy-container-to-registry
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
          project-name: revive
          service-type: client
          tech-name: reactjs
          dockerfile-path: ./docker/client/reactjs/Dockerfile