
name: "JUnit Test"
on: [push]
jobs:
  gradle:
    strategy:
      matrix:
        #TODO -remove comment before ver2 tag
        #os: [ubuntu-latest, macos-latest, windows-latest]
        #version : [11, 17, 18]
        os: [ubuntu-latest]
        version : [17]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.version }}
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
